### ISSUE TITLE
A minor problem in the replication

### ISSUE THREAD

**Issue by shaoyuyoung** [ise-uiuc/neuri-artifact#4]
Hi, Jiawei @ganler 

Here is a minor bug (maybe?) when I replicated the experiment.

When I went into [S2: Collect coverage](https://github.com/ise-uiuc/neuri-artifact#s2-collect-coverage) [For PyTorch](https://github.com/ise-uiuc/neuri-artifact#for-pytorch-1)

After I executed the command below

```
python experiments/process_profraws.py --root $(pwd)/gen/torch-neuri-n5.models    \
                                       --llvm-config-path $(which llvm-config-14) \
                                       --instrumented-libs "$(pwd)/build/pytorch-cov/build/lib/libtorch_cpu.so" "$(pwd)/build/pytorch-cov/build/lib/libtorch.so" \
                                        --batch-size 1000 --parallel $(nproc)
``` 

An error occurred below

```
Traceback (most recent call last):
  File "experiments/process_profraws.py", line 197, in <module>
    with tempfile.TemporaryDirectory(dir="/coconut/jinjun-data/tmp") as tmpdirname:
  File "/opt/conda/envs/cov/lib/python3.8/tempfile.py", line 780, in __init__
    self.name = mkdtemp(suffix, prefix, dir)
  File "/opt/conda/envs/cov/lib/python3.8/tempfile.py", line 358, in mkdtemp
    _os.mkdir(file, 0o700)
FileNotFoundError: [Errno 2] No such file or directory: '/coconut/jinjun-data/tmp/tmpse6eo_89'
```

I think the problem is in the following line of code
https://github.com/ise-uiuc/neuri-artifact/blob/42b01a3edf5f2e90ea9d5957b765ada45ed4fad9/experiments/process_profraws.py#L197

Maybe we just need to remove the param `dir="/coconut/jinjun-data/tmp"`?

Then the error is solved for me💯

**Comment by ganler** [comment]
Thanks for pointing out the bug! It is now fixed. :)

**Comment by shaoyuyoung** [comment]
Congratulations on your best paper award! 

I really admire your solid work. Neuri deserves this award! 😄
